//! `aegis shell-init <shell>` — route a bare `pnpm install` through the gate.
//!
//! The gate only helps if it is on the path a human actually types, and
//! nobody types `aegis pnpm install`. This emits shell functions that do it
//! for them.
//!
//! Two deliberate choices, both about not breaking someone's shell:
//!
//! - `--install` writes an **eval line**, never the snippet body. Upgrading
//!   aegis then upgrades the wrapper, and a future syntax error costs one
//!   message per shell start instead of aborting the rest of the rc file.
//! - Every error path prints to stderr and leaves **stdout empty**, so
//!   `eval "$(aegis shell-init nu)"` degrades to `eval ""` rather than
//!   evaluating an error message.
//!
//! What this does *not* cover, and the docs say so rather than implying
//! otherwise: non-interactive shells. CI, `make`, `mise run`, and
//! `package.json` scripts never source an rc file, so the wrapper is absent
//! there by construction. `aegis ci` and `aegis hook --install` are the
//! answer for those.

use std::path::{Path, PathBuf};
use std::process::ExitCode;

use crate::markers::{inject, strip};
use crate::pm::Pm;

const MARKER_START: &str = "# >>> aegis shell integration (do not edit) >>>";
const MARKER_END: &str = "# <<< aegis shell integration <<<";

/// Shells we can generate for. Deliberately *not* `clap_complete::Shell`:
/// that enum contains shells we cannot emit, and would silently accept them.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum InitShell {
    Zsh,
    Bash,
    Fish,
}

impl InitShell {
    fn parse(s: &str) -> Option<InitShell> {
        match s {
            "zsh" => Some(InitShell::Zsh),
            // The bash generator is POSIX-clean, so `sh` gets the same one.
            "bash" | "sh" => Some(InitShell::Bash),
            "fish" => Some(InitShell::Fish),
            _ => None,
        }
    }

    fn name(self) -> &'static str {
        match self {
            InitShell::Zsh => "zsh",
            InitShell::Bash => "bash",
            InitShell::Fish => "fish",
        }
    }

    /// Detect from `$SHELL`.
    fn detect() -> Option<InitShell> {
        let sh = std::env::var("SHELL").ok()?;
        let base = Path::new(&sh).file_name()?.to_str()?;
        InitShell::parse(base)
    }
}

/// The managers wrapped when the user does not say. cargo, pip and go are
/// opt-in: `go build` and `cargo check` run constantly and install nothing,
/// so wrapping them buys an extra exec on every inner-loop command.
const DEFAULT_PMS: [Pm; 4] = [Pm::Npm, Pm::Pnpm, Pm::Yarn, Pm::Bun];

/// Parse `--pm npm,pnpm`. Every value is checked against the fixed set —
/// this is the injection boundary, and `--pm 'x; rm -rf ~'` must not reach a
/// generated `eval`.
fn parse_pms(csv: &str) -> Result<Vec<Pm>, String> {
    let mut out = Vec::new();
    for part in csv.split(',') {
        let t = part.trim();
        if t.is_empty() {
            continue;
        }
        match Pm::parse(t) {
            Some(pm) if !out.contains(&pm) => out.push(pm),
            Some(_) => {}
            None => return Err(format!("unknown package manager {t:?}")),
        }
    }
    if out.is_empty() {
        return Err("no package managers selected".into());
    }
    Ok(out)
}

/// The snippet itself.
pub(crate) fn snippet(shell: InitShell, pms: &[Pm]) -> String {
    let names: Vec<&str> = pms.iter().map(|p| p.name()).collect();
    let list = names.join(",");
    let version = env!("CARGO_PKG_VERSION");

    match shell {
        InitShell::Fish => {
            let mut fns = String::new();
            for n in &names {
                fns.push_str(&format!(
                    "    function {n} --wraps {n}; _aegis_gate {n} $argv; end\n"
                ));
            }
            format!(
                "# aegis shell integration — generated by `aegis shell-init fish`\n\
                 # Bypass one command: `command pnpm install` or `AEGIS_NO_GATE=1 pnpm install`\n\
                 if status is-interactive; or set -q AEGIS_SHELL_INIT_FORCE\n\
                 \x20   set -gx AEGIS_SHELL_INIT {version}\n\
                 \x20   set -gx AEGIS_SHELL_PMS {list}\n\
                 \n\
                 \x20   function _aegis_gate\n\
                 \x20       set -l pm $argv[1]\n\
                 \x20       set -e argv[1]\n\
                 \x20       if set -q AEGIS_NO_GATE; or set -q AEGIS_GATE_ACTIVE; or not command -q aegis\n\
                 \x20           command $pm $argv\n\
                 \x20           return $status\n\
                 \x20       end\n\
                 \x20       command aegis $pm $argv\n\
                 \x20   end\n\
                 \n{fns}end\n"
            )
        }
        _ => {
            let mut fns = String::new();
            for n in &names {
                fns.push_str(&format!("  {n}() {{ _aegis_gate {n} \"$@\"; }}\n"));
            }
            format!(
                "# aegis shell integration — generated by `aegis shell-init {shell}`\n\
                 # Bypass one command: `command pnpm install` or `AEGIS_NO_GATE=1 pnpm install`\n\
                 _aegis_interactive=0\n\
                 case $- in *i*) _aegis_interactive=1 ;; esac\n\
                 if [ \"$_aegis_interactive\" = 1 ] || [ -n \"${{AEGIS_SHELL_INIT_FORCE-}}\" ]; then\n\
                 \x20 AEGIS_SHELL_INIT={version}\n\
                 \x20 AEGIS_SHELL_PMS={list}\n\
                 \x20 export AEGIS_SHELL_INIT AEGIS_SHELL_PMS\n\
                 \n\
                 \x20 _aegis_gate() {{\n\
                 \x20   _aegis_pm=$1; shift\n\
                 \x20   if [ -n \"${{AEGIS_NO_GATE-}}\" ] || [ -n \"${{AEGIS_GATE_ACTIVE-}}\" ]; then\n\
                 \x20     command \"$_aegis_pm\" \"$@\"; return $?\n\
                 \x20   fi\n\
                 \x20   if ! command -v aegis >/dev/null 2>&1; then\n\
                 \x20     command \"$_aegis_pm\" \"$@\"; return $?\n\
                 \x20   fi\n\
                 \x20   command aegis \"$_aegis_pm\" \"$@\"\n\
                 \x20 }}\n\
                 \n{fns}fi\n\
                 unset _aegis_interactive\n",
                shell = shell.name()
            )
        }
    }
}

impl std::fmt::Display for InitShell {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.name())
    }
}

/// The line written into the rc file. Not the body — see the module docs.
fn rc_block(shell: InitShell, pms: &[Pm]) -> String {
    let list: Vec<&str> = pms.iter().map(|p| p.name()).collect();
    let list = list.join(",");
    match shell {
        InitShell::Fish => {
            format!("if command -q aegis\n    aegis shell-init fish --pm {list} | source\nend")
        }
        _ => format!(
            "if command -v aegis >/dev/null 2>&1; then\n  \
             eval \"$(aegis shell-init {shell} --pm {list})\"\nfi",
            shell = shell.name()
        ),
    }
}

/// Where the block goes.
fn rc_path(shell: InitShell) -> Option<PathBuf> {
    let home = std::env::var_os("HOME").map(PathBuf::from)?;
    Some(match shell {
        InitShell::Zsh => std::env::var_os("ZDOTDIR")
            .map(PathBuf::from)
            .unwrap_or_else(|| home.clone())
            .join(".zshrc"),
        InitShell::Bash => {
            let rc = home.join(".bashrc");
            let profile = home.join(".bash_profile");
            if rc.exists() || !profile.exists() {
                rc
            } else {
                profile
            }
        }
        InitShell::Fish => std::env::var_os("XDG_CONFIG_HOME")
            .map(PathBuf::from)
            .unwrap_or_else(|| home.join(".config"))
            .join("fish")
            .join("config.fish"),
    })
}

fn in_ci() -> bool {
    ["CI", "GITHUB_ACTIONS", "GITLAB_CI", "BUILDKITE"]
        .iter()
        .any(|k| std::env::var_os(k).is_some_and(|v| !v.is_empty()))
}

pub(crate) fn run(
    shell: Option<String>,
    pm_csv: Option<String>,
    all: bool,
    install: bool,
    uninstall: bool,
    rc: Option<String>,
    force: bool,
) -> ExitCode {
    let shell = match shell.as_deref() {
        Some(s) => match InitShell::parse(s) {
            Some(sh) => sh,
            None => {
                // stdout stays empty so `eval "$(...)"` is a no-op.
                eprintln!("aegis: unsupported shell {s:?} (zsh, bash, fish)");
                return ExitCode::from(2);
            }
        },
        None => match InitShell::detect() {
            Some(sh) => sh,
            None => {
                eprintln!("aegis: could not detect your shell — pass one (zsh, bash, fish)");
                return ExitCode::from(2);
            }
        },
    };

    let pms = if all {
        Pm::ALL.to_vec()
    } else {
        match pm_csv.as_deref() {
            Some(csv) => match parse_pms(csv) {
                Ok(v) => v,
                Err(e) => {
                    eprintln!("aegis: {e}");
                    return ExitCode::from(2);
                }
            },
            None => DEFAULT_PMS.to_vec(),
        }
    };

    if !install && !uninstall {
        print!("{}", snippet(shell, &pms));
        return ExitCode::SUCCESS;
    }

    let path = match rc.map(PathBuf::from).or_else(|| rc_path(shell)) {
        Some(p) => p,
        None => {
            eprintln!("aegis: could not work out which rc file to edit — pass --rc <path>");
            return ExitCode::from(2);
        }
    };

    if install && in_ci() && !force {
        eprintln!(
            "aegis: refusing to install shell integration in CI — an rc file is \
             never sourced there. Use `aegis ci <lockfile>` in your workflow. \
             Override with --force."
        );
        return ExitCode::from(2);
    }

    let existing = std::fs::read_to_string(&path).unwrap_or_default();

    if uninstall {
        match strip(&existing, MARKER_START, MARKER_END) {
            // Nothing of ours: do not rewrite the file at all.
            None => {
                eprintln!(
                    "aegis: shell integration not installed in {}",
                    path.display()
                );
                ExitCode::SUCCESS
            }
            Some(out) => {
                // Deliberately unlike hook.rs, which deletes a hook file it
                // has emptied: an emptied rc file is written back, never
                // removed. Deleting someone's .zshrc is unrecoverable.
                if let Err(e) = std::fs::write(&path, out) {
                    eprintln!("aegis: write {}: {e}", path.display());
                    return ExitCode::from(2);
                }
                eprintln!("aegis: removed shell integration from {}", path.display());
                ExitCode::SUCCESS
            }
        }
    } else {
        let out = inject(&existing, &rc_block(shell, &pms), MARKER_START, MARKER_END);
        if let Err(e) = std::fs::write(&path, out) {
            eprintln!("aegis: write {}: {e}", path.display());
            return ExitCode::from(2);
        }
        let names: Vec<&str> = pms.iter().map(|p| p.name()).collect();
        eprintln!(
            "aegis: wrote shell integration to {} (wrapping {}).\n\
             Restart your shell, or run: exec {shell}",
            path.display(),
            names.join(", ")
        );
        ExitCode::SUCCESS
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_function_is_emitted_for_each_requested_manager_and_no_others() {
        let s = snippet(InitShell::Bash, &[Pm::Pnpm]);
        assert!(s.contains("  pnpm() { _aegis_gate pnpm \"$@\"; }"));
        // Leading indent matters: "pnpm() {" contains "npm() {".
        assert!(!s.contains("  npm() {"));
        assert!(!s.contains("  yarn() {"));

        let f = snippet(InitShell::Fish, &[Pm::Npm, Pm::Bun]);
        assert!(f.contains("function npm --wraps npm"));
        assert!(f.contains("function bun --wraps bun"));
        assert!(!f.contains("function yarn"));
    }

    #[test]
    fn every_snippet_carries_its_guards() {
        for sh in [InitShell::Zsh, InitShell::Bash, InitShell::Fish] {
            let s = snippet(sh, &DEFAULT_PMS);
            // Bypasses, both layers.
            assert!(s.contains("AEGIS_NO_GATE"), "{sh}: missing bypass");
            assert!(
                s.contains("AEGIS_GATE_ACTIVE"),
                "{sh}: missing re-entry guard"
            );
            // Never break the shell when aegis is gone — checked at CALL time,
            // so removing the binary mid-session cannot leave a broken pnpm.
            assert!(
                s.contains("command -v aegis") || s.contains("command -q aegis"),
                "{sh}: missing aegis presence check"
            );
            // Interactive-only.
            assert!(
                s.contains("case $- in *i*)") || s.contains("status is-interactive"),
                "{sh}: missing interactive guard"
            );
            // Bypass paths must go through `command` so a shell-level loop is
            // structurally impossible.
            assert!(s.contains("command "), "{sh}: missing command builtin use");
        }
    }

    #[test]
    fn shell_parsing_rejects_what_it_cannot_emit() {
        assert_eq!(InitShell::parse("zsh"), Some(InitShell::Zsh));
        assert_eq!(InitShell::parse("sh"), Some(InitShell::Bash));
        assert_eq!(InitShell::parse("fish"), Some(InitShell::Fish));
        for bad in ["powershell", "nu", "elvish", "xonsh", ""] {
            assert_eq!(InitShell::parse(bad), None, "{bad} must be rejected");
        }
    }

    #[test]
    fn pm_list_is_validated_because_it_reaches_an_eval() {
        assert_eq!(parse_pms("npm,pnpm").unwrap(), vec![Pm::Npm, Pm::Pnpm]);
        assert_eq!(parse_pms(" npm , npm ").unwrap(), vec![Pm::Npm]);
        // The injection boundary.
        assert!(parse_pms("x; rm -rf ~").is_err());
        assert!(parse_pms("npm,$(whoami)").is_err());
        assert!(parse_pms("").is_err());
    }

    #[test]
    fn the_rc_block_evals_rather_than_pasting_the_body() {
        let b = rc_block(InitShell::Zsh, &[Pm::Pnpm]);
        assert!(b.contains("eval \"$(aegis shell-init zsh --pm pnpm)\""));
        // The body must NOT be inlined, or upgrades never reach the user.
        assert!(!b.contains("_aegis_gate()"));
        // Guarded, so a missing aegis does not poison the rc's exit status.
        assert!(b.contains("command -v aegis"));

        let f = rc_block(InitShell::Fish, &[Pm::Npm]);
        assert!(f.contains("| source"));
        assert!(f.contains("command -q aegis"));
    }

    #[test]
    fn injecting_twice_leaves_one_block() {
        let once = inject(
            "# mine\n",
            &rc_block(InitShell::Bash, &DEFAULT_PMS),
            MARKER_START,
            MARKER_END,
        );
        let twice = inject(
            &once,
            &rc_block(InitShell::Bash, &DEFAULT_PMS),
            MARKER_START,
            MARKER_END,
        );
        assert_eq!(twice.matches(MARKER_START).count(), 1);
        assert!(twice.starts_with("# mine\n"));
    }
}
