package locksnap

import (
	"testing"

	"github.com/qwexvf/aegis-cli/internal/domain"
)

func TestParseCargoLock(t *testing.T) {
	in := []byte(`# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "serde"
version = "1.0.193"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "abc"

[[package]]
name = "tokio"
version = "1.35.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = ["mio", "pin-project-lite"]

[[package]]
name = "mio"
version = "0.8.10"
`)
	deps, err := parseCargoLock(in, nil)
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if len(deps) != 3 {
		t.Fatalf("got %d deps, want 3", len(deps))
	}
	for _, d := range deps {
		if d.Ecosystem != domain.EcoCrates {
			t.Errorf("ecosystem = %v, want crates", d.Ecosystem)
		}
	}
	versions := map[string]string{}
	for _, d := range deps {
		versions[d.Name] = d.Version
	}
	if versions["serde"] != "1.0.193" {
		t.Errorf("serde = %q", versions["serde"])
	}
	if versions["tokio"] != "1.35.1" {
		t.Errorf("tokio = %q", versions["tokio"])
	}
}
