package locksnap

import (
	"os"
	"path/filepath"
	"testing"
)

const samplePackageJSON = `{
  "name": "demo",
  "dependencies": { "lodash": "^4.17.0" },
  "devDependencies": { "react": "^18.0.0" }
}`

func writeProject(t *testing.T, files map[string]string) string {
	t.Helper()
	dir := t.TempDir()
	for name, content := range files {
		path := filepath.Join(dir, name)
		os.MkdirAll(filepath.Dir(path), 0o755)
		if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	return dir
}

// --- npm v3 (modern) ----------------------------------------------------

const npmV3Lock = `{
  "name": "demo",
  "lockfileVersion": 3,
  "packages": {
    "": { "name": "demo", "version": "1.0.0" },
    "node_modules/lodash": {
      "version": "4.17.21",
      "integrity": "sha512-aaa"
    },
    "node_modules/react": {
      "version": "18.2.0",
      "integrity": "sha512-bbb"
    },
    "node_modules/react/node_modules/loose-envify": {
      "version": "1.4.0",
      "integrity": "sha512-ccc"
    }
  }
}`

func TestScanner_NpmV3(t *testing.T) {
	dir := writeProject(t, map[string]string{
		"package.json":      samplePackageJSON,
		"package-lock.json": npmV3Lock,
	})
	deps, err := NewScanner().ScanProject(dir)
	if err != nil {
		t.Fatal(err)
	}
	if len(deps) != 3 {
		t.Fatalf("expected 3 deps, got %d: %+v", len(deps), deps)
	}
	// Sorted by name.
	if deps[0].Name != "lodash" || deps[1].Name != "loose-envify" || deps[2].Name != "react" {
		t.Errorf("unexpected order/names: %+v", deps)
	}
	// Integrity preserved.
	if deps[0].Integrity != "sha512-aaa" {
		t.Errorf("integrity lost: %+v", deps[0])
	}
	// Direct flag from package.json.
	if !deps[0].Direct || !deps[2].Direct || deps[1].Direct {
		t.Errorf("direct flags wrong: lodash=%v react=%v loose-envify=%v",
			deps[0].Direct, deps[2].Direct, deps[1].Direct)
	}
}

// --- npm v1 (legacy) ----------------------------------------------------

const npmV1Lock = `{
  "name": "demo",
  "lockfileVersion": 1,
  "dependencies": {
    "lodash": { "version": "4.17.21", "integrity": "sha512-aaa" },
    "react": {
      "version": "18.2.0",
      "integrity": "sha512-bbb",
      "dependencies": {
        "loose-envify": { "version": "1.4.0", "integrity": "sha512-ccc" }
      }
    }
  }
}`

func TestScanner_NpmV1(t *testing.T) {
	dir := writeProject(t, map[string]string{
		"package.json":      samplePackageJSON,
		"package-lock.json": npmV1Lock,
	})
	deps, _ := NewScanner().ScanProject(dir)
	if len(deps) != 3 {
		t.Fatalf("expected 3 deps from v1 tree, got %d: %+v", len(deps), deps)
	}
}

// --- pnpm ---------------------------------------------------------------

const pnpmLock = `lockfileVersion: '6.0'

dependencies:
  lodash:
    specifier: ^4.17.0
    version: 4.17.21

packages:

  /lodash@4.17.21:
    resolution: {integrity: sha512-aaa}
    dev: false

  /react@18.2.0:
    resolution: {integrity: sha512-bbb}

  /loose-envify@1.4.0(react@18.2.0):
    resolution: {integrity: sha512-ccc}

  /@types/lodash@4.14.0:
    resolution: {integrity: sha512-ddd}
    dev: true

settings:
  autoInstallPeers: true
`

func TestScanner_Pnpm(t *testing.T) {
	dir := writeProject(t, map[string]string{
		"package.json":   samplePackageJSON,
		"pnpm-lock.yaml": pnpmLock,
	})
	deps, err := NewScanner().ScanProject(dir)
	if err != nil {
		t.Fatal(err)
	}
	if len(deps) != 4 {
		t.Fatalf("expected 4 deps, got %d: %+v", len(deps), deps)
	}
	names := make([]string, len(deps))
	for i, d := range deps {
		names[i] = d.Name
	}
	want := []string{"@types/lodash", "lodash", "loose-envify", "react"}
	for i, w := range want {
		if names[i] != w {
			t.Errorf("dep[%d] name = %q, want %q (full: %v)", i, names[i], w, names)
		}
	}
}

// --- yarn classic -------------------------------------------------------

const yarnClassicLock = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

lodash@^4.17.0, lodash@^4.17.21:
  version "4.17.21"
  resolved "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz"
  integrity sha512-aaa==

"@types/lodash@^4.14.0":
  version "4.14.0"
  resolved "https://registry.npmjs.org/@types/lodash/-/lodash-4.14.0.tgz"
  integrity sha512-ddd==

react@^18.0.0:
  version "18.2.0"
  resolved "https://registry.npmjs.org/react/-/react-18.2.0.tgz"
  integrity sha512-bbb==
  dependencies:
    loose-envify "^1.1.0"

loose-envify@^1.1.0:
  version "1.4.0"
  resolved "https://registry.npmjs.org/loose-envify/-/loose-envify-1.4.0.tgz"
  integrity sha512-ccc==
`

func TestScanner_YarnClassic(t *testing.T) {
	dir := writeProject(t, map[string]string{
		"package.json": samplePackageJSON,
		"yarn.lock":    yarnClassicLock,
	})
	deps, err := NewScanner().ScanProject(dir)
	if err != nil {
		t.Fatal(err)
	}
	if len(deps) != 4 {
		t.Fatalf("expected 4 deps, got %d: %+v", len(deps), deps)
	}
	names := make(map[string]string)
	for _, d := range deps {
		names[d.Name] = d.Version
	}
	if names["lodash"] != "4.17.21" || names["@types/lodash"] != "4.14.0" {
		t.Errorf("unexpected resolution: %+v", names)
	}
}

// --- bun ----------------------------------------------------------------

const bunLock = `{
  // bun lockfile, comments are tolerated
  "lockfileVersion": 1,
  "packages": {
    "lodash": ["lodash@4.17.21", "sha512-aaa==", {}],
    "react":  ["react@18.2.0", "sha512-bbb==", {}],
    "react/loose-envify": ["loose-envify@1.4.0", "sha512-ccc=="],
  }
}
`

func TestScanner_Bun(t *testing.T) {
	dir := writeProject(t, map[string]string{
		"package.json": samplePackageJSON,
		"bun.lock":     bunLock,
	})
	deps, err := NewScanner().ScanProject(dir)
	if err != nil {
		t.Fatal(err)
	}
	if len(deps) != 3 {
		t.Fatalf("expected 3 deps, got %d: %+v", len(deps), deps)
	}
	names := map[string]string{}
	for _, d := range deps {
		names[d.Name] = d.Version
	}
	if names["lodash"] != "4.17.21" || names["react"] != "18.2.0" || names["loose-envify"] != "1.4.0" {
		t.Errorf("unexpected resolutions: %+v", names)
	}
}

// --- detection priority -------------------------------------------------

func TestScanner_PrefersPnpmOverPackageLock(t *testing.T) {
	dir := writeProject(t, map[string]string{
		"package.json":      samplePackageJSON,
		"package-lock.json": npmV3Lock,
		"pnpm-lock.yaml":    pnpmLock,
	})
	deps, err := NewScanner().ScanProject(dir)
	if err != nil {
		t.Fatal(err)
	}
	// pnpm fixture has 4 entries; npm fixture has 3. We expect 4 → pnpm chosen.
	if len(deps) != 4 {
		t.Errorf("expected pnpm to win (4 deps), got %d", len(deps))
	}
}

// --- empty project ------------------------------------------------------

func TestScanner_NoLockfileReturnsEmpty(t *testing.T) {
	dir := writeProject(t, map[string]string{"package.json": samplePackageJSON})
	deps, err := NewScanner().ScanProject(dir)
	if err != nil {
		t.Fatal(err)
	}
	if len(deps) != 0 {
		t.Errorf("expected empty for no lockfile, got %+v", deps)
	}
}

// --- direct deps without package.json -----------------------------------

func TestScanner_NoManifestNoDirectFlags(t *testing.T) {
	dir := writeProject(t, map[string]string{
		"package-lock.json": npmV3Lock,
	})
	deps, err := NewScanner().ScanProject(dir)
	if err != nil {
		t.Fatal(err)
	}
	for _, d := range deps {
		if d.Direct {
			t.Errorf("expected all Direct=false without package.json, got %+v", d)
		}
	}
}
