.nh
.TH "AEGIS" "1" "May 2026" "aegis 0.1.0-demo" "Aegis Manual"

.SH NAME
aegis-image - Scan OCI / Docker container images for supply-chain risks


.SH SYNOPSIS
\fBaegis image [flags]\fP


.SH DESCRIPTION
Scan OCI / Docker container images for supply-chain risks


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for image


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-v\fP, \fB--verbose\fP[=false]
	enable debug-level structured logging to stderr


.SH SEE ALSO
\fBaegis(1)\fP, \fBaegis-image-scan(1)\fP
