.nh
.TH "AEGIS" "1" "May 2026" "aegis 0.1.0-demo" "Aegis Manual"

.SH NAME
aegis-admin - Operator utilities (key generation, etc.)


.SH SYNOPSIS
\fBaegis admin [flags]\fP


.SH DESCRIPTION
Operator utilities (key generation, etc.)


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for admin


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-v\fP, \fB--verbose\fP[=false]
	enable debug-level structured logging to stderr


.SH SEE ALSO
\fBaegis(1)\fP, \fBaegis-admin-gen-key(1)\fP
