.nh
.TH "AEGIS" "1" "May 2026" "aegis 0.1.0-demo" "Aegis Manual"

.SH NAME
aegis-allowlist-list - Show all allowlist rules (builtin + user + project)


.SH SYNOPSIS
\fBaegis allowlist list [flags]\fP


.SH DESCRIPTION
Show all allowlist rules (builtin + user + project)


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for list

.PP
\fB--source\fP=""
	filter by source (builtin|user|project)


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-v\fP, \fB--verbose\fP[=false]
	enable debug-level structured logging to stderr


.SH SEE ALSO
\fBaegis-allowlist(1)\fP
