.nh
.TH "AEGIS" "1" "May 2026" "aegis 0.1.0-demo" "Aegis Manual"

.SH NAME
aegis-cloud - Cloud-backed analysis commands


.SH SYNOPSIS
\fBaegis cloud [flags]\fP


.SH DESCRIPTION
Cloud-backed analysis commands


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for cloud


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-v\fP, \fB--verbose\fP[=false]
	enable debug-level structured logging to stderr


.SH SEE ALSO
\fBaegis(1)\fP, \fBaegis-cloud-analyze(1)\fP
