.nh
.TH "AEGIS" "1" "May 2026" "aegis 0.1.0-demo" "Aegis Manual"

.SH NAME
aegis-snapshot-show - Print the saved snapshot. By default only direct deps are shown.


.SH SYNOPSIS
\fBaegis snapshot show [flags]\fP


.SH DESCRIPTION
Print the saved snapshot. By default only direct deps are shown.


.SH OPTIONS
\fB--all\fP[=false]
	show transitive deps as well

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for show

.PP
\fB--json\fP[=false]
	emit machine-readable JSON

.PP
\fB--used-only\fP[=false]
	hide deps marked unreachable from project source


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-v\fP, \fB--verbose\fP[=false]
	enable debug-level structured logging to stderr


.SH SEE ALSO
\fBaegis-snapshot(1)\fP
