.nh
.TH "AEGIS" "1" "May 2026" "aegis 0.1.0-demo" "Aegis Manual"

.SH NAME
aegis-hook - Install / uninstall the aegis pre-commit hook


.SH SYNOPSIS
\fBaegis hook [flags]\fP


.SH DESCRIPTION
Install / uninstall the aegis pre-commit hook


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for hook


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-v\fP, \fB--verbose\fP[=false]
	enable debug-level structured logging to stderr


.SH SEE ALSO
\fBaegis(1)\fP, \fBaegis-hook-install(1)\fP, \fBaegis-hook-uninstall(1)\fP
