.nh
.TH "AEGIS" "1" "May 2026" "aegis 0.1.0-demo" "Aegis Manual"

.SH NAME
aegis-audit-tail - Show the most recent audit entries


.SH SYNOPSIS
\fBaegis audit tail [flags]\fP


.SH DESCRIPTION
Show the most recent audit entries


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for tail

.PP
\fB-n\fP, \fB--n\fP=20
	show the last N entries (0 = all)


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-v\fP, \fB--verbose\fP[=false]
	enable debug-level structured logging to stderr


.SH SEE ALSO
\fBaegis-audit(1)\fP
