.nh
.TH "AEGIS" "1" "May 2026" "aegis 0.1.0-demo" "Aegis Manual"

.SH NAME
aegis-snapshot-enrich - Run AST analysis over the saved snapshot to populate fingerprints


.SH SYNOPSIS
\fBaegis snapshot enrich [flags]\fP


.SH DESCRIPTION
Run AST analysis over the saved snapshot to populate fingerprints


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for enrich


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-v\fP, \fB--verbose\fP[=false]
	enable debug-level structured logging to stderr


.SH SEE ALSO
\fBaegis-snapshot(1)\fP
