.nh
.TH "AEGIS" "1" "May 2026" "aegis 0.1.0-demo" "Aegis Manual"

.SH NAME
aegis-snapshot-verify - Verify aegis.lock is loadable and matches the current schema


.SH SYNOPSIS
\fBaegis snapshot verify [flags]\fP


.SH DESCRIPTION
Verify aegis.lock is loadable and matches the current schema


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for verify


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-v\fP, \fB--verbose\fP[=false]
	enable debug-level structured logging to stderr


.SH SEE ALSO
\fBaegis-snapshot(1)\fP
