.nh
.TH "AEGIS" "1" "May 2026" "aegis 0.1.0-demo" "Aegis Manual"

.SH NAME
aegis-allowlist - Manage capability suppressions for specific packages


.SH SYNOPSIS
\fBaegis allowlist [flags]\fP


.SH DESCRIPTION
Manage capability suppressions for specific packages


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for allowlist


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-v\fP, \fB--verbose\fP[=false]
	enable debug-level structured logging to stderr


.SH SEE ALSO
\fBaegis(1)\fP, \fBaegis-allowlist-add(1)\fP, \fBaegis-allowlist-list(1)\fP, \fBaegis-allowlist-remove(1)\fP, \fBaegis-allowlist-sync(1)\fP, \fBaegis-allowlist-test(1)\fP, \fBaegis-allowlist-verify(1)\fP
