.nh
.TH "AEGIS" "1" "May 2026" "aegis 0.1.0-demo" "Aegis Manual"

.SH NAME
aegis-allowlist-verify - Validate user and project allowlist YAML files


.SH SYNOPSIS
\fBaegis allowlist verify [flags]\fP


.SH DESCRIPTION
Validate user and project allowlist YAML files


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for verify


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-v\fP, \fB--verbose\fP[=false]
	enable debug-level structured logging to stderr


.SH SEE ALSO
\fBaegis-allowlist(1)\fP
