.nh
.TH "AEGIS" "1" "May 2026" "aegis 0.1.0-demo" "Aegis Manual"

.SH NAME
aegis-snapshot - Save / show / diff project dependency snapshots


.SH SYNOPSIS
\fBaegis snapshot [flags]\fP


.SH DESCRIPTION
Save / show / diff project dependency snapshots


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for snapshot


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-v\fP, \fB--verbose\fP[=false]
	enable debug-level structured logging to stderr


.SH SEE ALSO
\fBaegis(1)\fP, \fBaegis-snapshot-diff(1)\fP, \fBaegis-snapshot-enrich(1)\fP, \fBaegis-snapshot-save(1)\fP, \fBaegis-snapshot-show(1)\fP, \fBaegis-snapshot-submit(1)\fP, \fBaegis-snapshot-verify(1)\fP
