.nh
.TH "AEGIS" "1" "May 2026" "aegis 0.1.0-demo" "Aegis Manual"

.SH NAME
aegis-allowlist-test - Show which allowlist rules suppress capabilities for a (eco, name, version)


.SH SYNOPSIS
\fBaegis allowlist test /@ [flags]\fP


.SH DESCRIPTION
Show which allowlist rules suppress capabilities for a (eco, name, version)


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for test


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-v\fP, \fB--verbose\fP[=false]
	enable debug-level structured logging to stderr


.SH SEE ALSO
\fBaegis-allowlist(1)\fP
