.nh
.TH "AEGIS" "1" "May 2026" "aegis 0.1.0-demo" "Aegis Manual"

.SH NAME
aegis-snapshot-submit - Post analyzed deps as community reports to the Aegis API


.SH SYNOPSIS
\fBaegis snapshot submit [flags]\fP


.SH DESCRIPTION
Post analyzed deps as community reports to the Aegis API


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for submit


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-v\fP, \fB--verbose\fP[=false]
	enable debug-level structured logging to stderr


.SH SEE ALSO
\fBaegis-snapshot(1)\fP
