.nh
.TH "AEGIS" "1" "May 2026" "aegis 0.1.0-demo" "Aegis Manual"

.SH NAME
aegis-cache-list - List cached decisions


.SH SYNOPSIS
\fBaegis cache list [flags]\fP


.SH DESCRIPTION
List cached decisions


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for list


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-v\fP, \fB--verbose\fP[=false]
	enable debug-level structured logging to stderr


.SH SEE ALSO
\fBaegis-cache(1)\fP
