.nh
.TH "AEGIS" "1" "May 2026" "aegis 0.1.0-demo" "Aegis Manual"

.SH NAME
aegis-cache - Inspect or clear the local decision cache


.SH SYNOPSIS
\fBaegis cache [flags]\fP


.SH DESCRIPTION
Inspect or clear the local decision cache


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for cache


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-v\fP, \fB--verbose\fP[=false]
	enable debug-level structured logging to stderr


.SH SEE ALSO
\fBaegis(1)\fP, \fBaegis-cache-clear(1)\fP, \fBaegis-cache-list(1)\fP
