.nh
.TH "AEGIS" "1" "May 2026" "aegis 0.1.0-demo" "Aegis Manual"

.SH NAME
aegis-snapshot-diff - Diff the saved snapshot against the live lockfile (or two explicit files)


.SH SYNOPSIS
\fBaegis snapshot diff [a.lock] [b.lock] [flags]\fP


.SH DESCRIPTION
Diff the saved snapshot against the live lockfile (or two explicit files)


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for diff


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-v\fP, \fB--verbose\fP[=false]
	enable debug-level structured logging to stderr


.SH SEE ALSO
\fBaegis-snapshot(1)\fP
