.nh
.TH "AEGIS" "1" "May 2026" "aegis 0.1.0-demo" "Aegis Manual"

.SH NAME
aegis-hook-uninstall - Remove the aegis pre-commit hook from the current project


.SH SYNOPSIS
\fBaegis hook uninstall [flags]\fP


.SH DESCRIPTION
Remove the aegis pre-commit hook from the current project


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for uninstall


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB-v\fP, \fB--verbose\fP[=false]
	enable debug-level structured logging to stderr


.SH SEE ALSO
\fBaegis-hook(1)\fP
